; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = generic

[env]
platform = ch32v
framework = noneos-sdk
upload_protocol = wch-link
debug_tool = wch-link
monitor_speed = 115200
build_unflags = -std=gnu++17
build_flags = -std=gnu++20

[env:generic]
board = genericCH32V203C8T6

[env:evt]
board = ch32v203c8t6_evt_r0

[env:generic_isp]
extends = env:generic
upload_protocol = isp

[env:evt_isp]
extends = env:evt
upload_protocol = isp
